# Generated by Django 4.0.6 on 2022-07-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=250, unique=True)),
                ('servertype', models.CharField(choices=[('windows', 'WINDOWS'), ('linux', 'LINUX'), ('mac', 'MAC'), ('unix', 'UNIX')], default='windows', max_length=250)),
                ('disktype', models.CharField(choices=[('hdd', 'HDD'), ('sdd', 'SDD'), ('san disk', 'SAN DISK')], default='hdd', max_length=250)),
                ('owner', models.CharField(choices=[('ppsc', 'PPSC'), ('fcgo', 'FCGO')], default='ppsc', max_length=250)),
                ('serverlocation', models.CharField(choices=[('cloud', 'CLOUD'), ('standalone', 'STANDALONE'), ('aws', 'AWS'), ('azure', 'AZURE')], default='cloud', max_length=250)),
                ('cpu', models.TextField()),
                ('ram', models.TextField()),
                ('ipaddress', models.CharField(max_length=250, unique=True)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('publicip', models.CharField(max_length=250, unique=True)),
                ('privateip', models.CharField(max_length=250, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
    ]
