# Generated by Django 4.0.6 on 2022-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetails',
            name='cpu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='ram',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=250),
        ),
    ]
